"""Seed data for the PMS backend.

The dataset mirrors the mock data bundled with the PMS_FrontEnd_v1.0 React application so that
end-to-end flows work without requiring an actual database during Phase 4.
"""

from __future__ import annotations

from copy import deepcopy
from typing import Any, Dict

SEED_DATA: Dict[str, Any] = {
    "users": [
        {
            "id": "1",
            "email": "admin@ai-project.com",
            "name": "시스템 관리자",
            "role": "system_admin",
            "department": "IT",
            "hashed_password": "$2b$12$4.n22XH3CHYEnbkg7Ky8w.Lz8n5ZPA5xw.9JCjuOQCYeCinvMy6nq",  # "admin123"
            "is_active": True,
        },
        {
            "id": "2",
            "email": "pm@ai-project.com",
            "name": "김승현 프로젝트관리자",
            "role": "project_manager",
            "department": "개발팀",
            "projects": ["1", "2"],
            "hashed_password": "$2b$12$4.n22XH3CHYEnbkg7Ky8w.Lz8n5ZPA5xw.9JCjuOQCYeCinvMy6nq",  # "pm123"
            "is_active": True,
        },
        {
            "id": "3",
            "email": "pl@ai-project.com",
            "name": "이승현 파트장",
            "role": "part_leader",
            "department": "프론트엔드팀",
            "projects": ["1"],
            "hashed_password": "$2b$12$4.n22XH3CHYEnbkg7Ky8w.Lz8n5ZPA5xw.9JCjuOQCYeCinvMy6nq",  # "pl123"
            "is_active": True,
        },
        {
            "id": "4",
            "email": "user@ai-project.com",
            "name": "박승현 개발자",
            "role": "user",
            "department": "개발팀",
            "projects": ["1", "2"],
            "hashed_password": "$2b$12$4.n22XH3CHYEnbkg7Ky8w.Lz8n5ZPA5xw.9JCjuOQCYeCinvMy6nq",  # "user123"
            "is_active": True,
        },
    ],
    "projects": [
        {
            "id": "1",
            "name": "AI 챗봇 개발",
            "description": "고객 서비스를 위한 AI 챗봇 시스템 구축",
            "ownerId": "1",
            "managerId": "2",
            "teamMembers": ["3", "4"],
            "department": "개발팀",
            "status": "completed",
            "priority": "high",
            "createdAt": "2024-01-15",
            "deadline": "2024-06-30",
            "taskCount": 12,
            "budget": {
                "planned": 150_000_000,
                "actual": 142_000_000,
                "currency": "KRW",
            },
            "kpis": {
                "onTimeDelivery": 95,
                "budgetAdherence": 105,
                "qualityScore": 92,
                "teamSatisfaction": 88,
            },
        },
        {
            "id": "2",
            "name": "모바일 앱 리뉴얼",
            "description": "기존 모바일 앱의 UI/UX 개선 및 성능 최적화",
            "ownerId": "1",
            "managerId": "2",
            "teamMembers": ["4"],
            "department": "개발팀",
            "status": "completed",
            "priority": "medium",
            "createdAt": "2024-02-01",
            "deadline": "2024-08-15",
            "taskCount": 8,
            "budget": {
                "planned": 80_000_000,
                "actual": 85_000_000,
                "currency": "KRW",
            },
            "kpis": {
                "onTimeDelivery": 100,
                "budgetAdherence": 94,
                "qualityScore": 89,
                "teamSatisfaction": 91,
            },
        },
        {
            "id": "3",
            "name": "데이터 분석 플랫폼",
            "description": "비즈니스 인텔리전스를 위한 데이터 분석 시스템",
            "ownerId": "1",
            "managerId": "2",
            "teamMembers": ["3", "4"],
            "department": "데이터팀",
            "status": "completed",
            "priority": "high",
            "createdAt": "2024-02-15",
            "deadline": "2024-09-30",
            "taskCount": 15,
            "budget": {
                "planned": 200_000_000,
                "actual": 190_000_000,
                "currency": "KRW",
            },
            "kpis": {
                "onTimeDelivery": 90,
                "budgetAdherence": 105,
                "qualityScore": 94,
                "teamSatisfaction": 85,
            },
        },
        {
            "id": "4",
            "name": "손해보험 지급심사 AI 자동화",
            "description": "OCR, RPA, AI 기반 보험금 지급심사 자동화 시스템 구축",
            "ownerId": "1",
            "managerId": "2",
            "teamMembers": ["3", "4"],
            "department": "AI사업부",
            "status": "active",
            "priority": "critical",
            "createdAt": "2025-03-01",
            "deadline": "2025-12-31",
            "taskCount": 156,
            "budget": {
                "planned": 500_000_000,
                "actual": 125_000_000,
                "currency": "KRW",
            },
            "kpis": {
                "onTimeDelivery": 85,
                "budgetAdherence": 75,
                "qualityScore": 87,
                "teamSatisfaction": 82,
            },
        },
    ],
    "project_members": [
        {"project_id": "1", "user_id": "2", "role": "project_manager"},
        {"project_id": "1", "user_id": "3", "role": "part_leader"},
        {"project_id": "1", "user_id": "4", "role": "user"},
        {"project_id": "2", "user_id": "2", "role": "project_manager"},
        {"project_id": "2", "user_id": "4", "role": "user"},
        {"project_id": "3", "user_id": "2", "role": "project_manager"},
        {"project_id": "3", "user_id": "3", "role": "part_leader"},
        {"project_id": "3", "user_id": "4", "role": "user"},
        {"project_id": "4", "user_id": "2", "role": "project_manager"},
        {"project_id": "4", "user_id": "3", "role": "part_leader"},
        {"project_id": "4", "user_id": "4", "role": "user"},
    ],
    "requirements": [
        {
            "id": "1",
            "reqIdString": "REQ-001",
            "trackingNumber": "CUST-2024-001",
            "title": "사용자는 이메일과 비밀번호로 로그인할 수 있어야 한다",
            "description": "기본적인 이메일 인증 기반 로그인 시스템을 구축하여 사용자가 안전하게 시스템에 접근할 수 있도록 한다.",
            "status": "in-progress",
            "projectId": "1",
            "createdAt": "2024-03-01",
            "updatedAt": "2024-03-05",
        },
        {
            "id": "2",
            "reqIdString": "REQ-002",
            "trackingNumber": "BIZ-REQ-002",
            "title": "소셜 로그인 기능 지원",
            "description": "구글, 카카오 등의 소셜 플랫폼을 통한 간편 로그인 기능을 제공한다.",
            "status": "defined",
            "projectId": "1",
            "createdAt": "2024-03-02",
            "updatedAt": "2024-03-02",
        },
        {
            "id": "3",
            "reqIdString": "REQ-003",
            "title": "프로젝트 대시보드 화면",
            "description": "사용자가 자신의 프로젝트 목록을 한눈에 볼 수 있는 대시보드를 제공한다.",
            "status": "done",
            "projectId": "1",
            "createdAt": "2024-02-28",
            "updatedAt": "2024-03-01",
        },
        {
            "id": "4",
            "reqIdString": "4-R1",
            "title": "OCR 엔진 개발",
            "description": "보험 서류 스캔 및 텍스트 추출 시스템 구축",
            "status": "in-progress",
            "projectId": "4",
            "createdAt": "2025-03-01",
            "updatedAt": "2025-03-05",
        },
        {
            "id": "5",
            "reqIdString": "4-R2",
            "title": "RPA 워크플로우 구축",
            "description": "자동화 프로세스 설계 및 구현",
            "status": "defined",
            "projectId": "4",
            "createdAt": "2025-03-04",
            "updatedAt": "2025-03-04",
        },
        {
            "id": "6",
            "reqIdString": "4-R3",
            "title": "AI 지급심사 모델 개발",
            "description": "기계학습 기반 자동 심사 시스템 구축",
            "status": "defined",
            "projectId": "4",
            "createdAt": "2025-03-06",
            "updatedAt": "2025-03-06",
        },
    ],
    "tasks": [
        {
            "id": "1",
            "title": "API 설계 문서 작성",
            "description": "RESTful API 엔드포인트 설계 및 문서화",
            "status": "done",
            "assignee": "김개발",
            "priority": "high",
            "createdAt": "2024-03-01",
            "projectId": "1",
            "requirementId": "1",
        },
        {
            "id": "1-1",
            "title": "사용자 API 엔드포인트 설계",
            "description": "로그인, 회원가입 관련 API 설계",
            "status": "done",
            "assignee": "김개발",
            "priority": "medium",
            "createdAt": "2024-03-02",
            "projectId": "1",
            "requirementId": "1",
            "parentTaskId": "1",
        },
        {
            "id": "1-2",
            "title": "API 문서화",
            "description": "Swagger를 활용한 API 문서 작성",
            "status": "done",
            "assignee": "김개발",
            "priority": "low",
            "createdAt": "2024-03-03",
            "projectId": "1",
            "requirementId": "1",
            "parentTaskId": "1",
        },
        {
            "id": "2",
            "title": "데이터베이스 스키마 설계",
            "description": "사용자 및 프로젝트 관련 테이블 설계",
            "status": "done",
            "assignee": "이백엔드",
            "priority": "high",
            "createdAt": "2024-03-02",
            "projectId": "1",
        },
        {
            "id": "3",
            "title": "UI 컴포넌트 구현",
            "description": "로그인 및 대시보드 컴포넌트 개발",
            "status": "done",
            "assignee": "박프론트",
            "priority": "medium",
            "createdAt": "2024-03-03",
            "projectId": "1",
            "requirementId": "1",
        },
        {
            "id": "4",
            "title": "로그인 기능 구현",
            "description": "JWT 기반 사용자 인증 시스템 구축",
            "status": "done",
            "assignee": "김개발",
            "priority": "high",
            "createdAt": "2024-02-25",
            "projectId": "1",
            "requirementId": "1",
        },
        {
            "id": "2-1",
            "title": "UI/UX 디자인 시스템 구축",
            "description": "일관된 디자인 가이드라인 및 컴포넌트 라이브러리 구축",
            "status": "done",
            "assignee": "이디자인",
            "priority": "high",
            "createdAt": "2024-02-15",
            "projectId": "2",
        },
        {
            "id": "2-2",
            "title": "성능 최적화",
            "description": "앱 로딩 속도 개선 및 메모리 사용량 최적화",
            "status": "done",
            "assignee": "박모바일",
            "priority": "medium",
            "createdAt": "2024-03-01",
            "projectId": "2",
        },
        {
            "id": "3-1",
            "title": "데이터 파이프라인 구축",
            "description": "ETL 프로세스 및 데이터 웨어하우스 구성",
            "status": "done",
            "assignee": "최데이터",
            "priority": "high",
            "createdAt": "2024-02-20",
            "projectId": "3",
        },
        {
            "id": "3-2",
            "title": "대시보드 개발",
            "description": "비즈니스 인텔리전스 대시보드 구현",
            "status": "done",
            "assignee": "강분석",
            "priority": "medium",
            "createdAt": "2024-03-10",
            "projectId": "3",
        },
        {
            "id": "4-1",
            "title": "OCR 엔진 개발",
            "description": "보험 서류 스캔 및 텍스트 추출 시스템 구축",
            "status": "in-progress",
            "assignee": "김AI개발",
            "priority": "critical",
            "createdAt": "2025-03-05",
            "projectId": "4",
            "requirementId": "4-R1",
        },
        {
            "id": "4-1-1",
            "title": "문서 이미지 전처리",
            "description": "스캔 품질 개선 및 노이즈 제거 알고리즘 구현",
            "status": "done",
            "assignee": "김AI개발",
            "priority": "high",
            "createdAt": "2025-03-06",
            "projectId": "4",
            "requirementId": "4-R1",
            "parentTaskId": "4-1",
        },
        {
            "id": "4-1-2",
            "title": "OCR 모델 훈련",
            "description": "보험 서류 특화 OCR 모델 학습 및 최적화",
            "status": "in-progress",
            "assignee": "김AI개발",
            "priority": "critical",
            "createdAt": "2025-03-08",
            "projectId": "4",
            "requirementId": "4-R1",
            "parentTaskId": "4-1",
        },
        {
            "id": "4-2",
            "title": "RPA 워크플로우 구축",
            "description": "자동화 프로세스 설계 및 구현",
            "status": "todo",
            "assignee": "이RPA엔지니어",
            "priority": "high",
            "createdAt": "2025-03-10",
            "projectId": "4",
            "requirementId": "4-R2",
        },
        {
            "id": "4-3",
            "title": "AI 지급심사 모델 개발",
            "description": "기계학습 기반 자동 심사 시스템 구축",
            "status": "todo",
            "assignee": "박ML엔지니어",
            "priority": "critical",
            "createdAt": "2025-03-12",
            "projectId": "4",
            "requirementId": "4-R3",
        },
        {
            "id": "4-4",
            "title": "통합 대시보드 개발",
            "description": "심사 현황 모니터링 및 관리 인터페이스",
            "status": "todo",
            "assignee": "최풀스택",
            "priority": "medium",
            "createdAt": "2025-03-15",
            "projectId": "4",
            "requirementId": "4-R4",
        },
        {
            "id": "4-5",
            "title": "데이터베이스 스키마 설계",
            "description": "보험 데이터 및 심사 결과 저장 구조 설계",
            "status": "in-progress",
            "assignee": "정DB관리자",
            "priority": "high",
            "createdAt": "2025-03-08",
            "projectId": "4",
            "requirementId": "4-R5",
        },
        {
            "id": "4-6",
            "title": "보안 및 개인정보보호 시스템",
            "description": "GDPR 및 개인정보보호법 준수 보안 체계 구축",
            "status": "todo",
            "assignee": "한보안전문가",
            "priority": "critical",
            "createdAt": "2025-03-18",
            "projectId": "4",
            "requirementId": "4-R6",
        },
        {
            "id": "4-7",
            "title": "성능 테스트 및 최적화",
            "description": "대용량 처리 성능 검증 및 시스템 최적화",
            "status": "todo",
            "assignee": "송QA엔지니어",
            "priority": "medium",
            "createdAt": "2025-03-20",
            "projectId": "4",
            "requirementId": "4-R7",
        },
    ],
    "sprints": [
        {
            "id": "1-1",
            "projectId": "1",
            "name": "Sprint 1 - 요구사항 분석",
            "goal": "챗봇 핵심 요구사항 도출 및 아키텍처 설계를 완료하여 개발 기반을 구축한다.",
            "status": "completed",
            "startDate": "2024-01-15",
            "endDate": "2024-02-15",
            "capacity": 40,
            "commitment": 35,
            "completed": 35,
            "createdAt": "2024-01-10",
        },
        {
            "id": "1-2",
            "projectId": "1",
            "name": "Sprint 2 - NLP 모델 개발",
            "goal": "BERT 기반 의도 분류 및 GPT 응답 생성 모델을 완성한다.",
            "status": "completed",
            "startDate": "2024-02-15",
            "endDate": "2024-04-15",
            "capacity": 80,
            "commitment": 75,
            "completed": 75,
            "createdAt": "2024-02-10",
        },
        {
            "id": "1-3",
            "projectId": "1",
            "name": "Sprint 3 - 대화 관리 시스템",
            "goal": "멀티턴 대화 상태 관리 및 세션 처리 시스템을 구축한다.",
            "status": "completed",
            "startDate": "2024-04-01",
            "endDate": "2024-05-30",
            "capacity": 50,
            "commitment": 45,
            "completed": 45,
            "createdAt": "2024-03-25",
        },
        {
            "id": "1-4",
            "projectId": "1",
            "name": "Sprint 4 - 통합 및 테스트",
            "goal": "CRM 연동 및 성능 테스트를 통해 서비스를 완성한다.",
            "status": "completed",
            "startDate": "2024-05-15",
            "endDate": "2024-06-30",
            "capacity": 35,
            "commitment": 30,
            "completed": 30,
            "createdAt": "2024-05-10",
        },
        {
            "id": "4-1",
            "projectId": "4",
            "name": "Sprint 1 - OCR 파이프라인",
            "goal": "보험 서류에 특화된 OCR 파이프라인을 구축한다.",
            "status": "active",
            "startDate": "2025-03-01",
            "endDate": "2025-04-15",
            "capacity": 90,
            "commitment": 85,
            "completed": 60,
            "createdAt": "2025-02-25",
        },
    ],
    "backlog_items": [
        {
            "id": "PB-101",
            "projectId": "4",
            "title": "보험금 지급 심사 규칙 엔진",
            "description": "보험금 지급 심사 비즈니스 규칙을 정의하고 자동화한다.",
            "storyPoints": 13,
            "priority": "critical",
            "status": "backlog",
            "type": "epic",
            "acceptance_criteria": [
                "심사 규칙은 관리 UI에서 CRUD 가능해야 한다",
                "규칙 엔진은 초당 50건 이상의 심사를 처리할 수 있어야 한다",
            ],
            "createdAt": "2025-03-01",
        },
        {
            "id": "PB-102",
            "projectId": "4",
            "title": "AI 모델 모니터링 대시보드",
            "description": "모델 추론 성능과 이상 징후를 실시간 모니터링한다.",
            "storyPoints": 8,
            "priority": "high",
            "status": "selected",
            "sprintId": "4-1",
            "type": "user-story",
            "acceptance_criteria": [
                "실시간 지표 (정확도, 지연시간, 오류율)를 표시한다",
                "임계치 초과 시 Slack 알림을 전송한다",
            ],
            "createdAt": "2025-03-02",
        },
        {
            "id": "PB-103",
            "projectId": "4",
            "title": "보험 청구 데이터 정합성 검증",
            "description": "데이터 품질을 유지하기 위한 검증 로직을 구축한다.",
            "storyPoints": 5,
            "priority": "medium",
            "status": "in-progress",
            "assignee": "정DB관리자",
            "type": "task",
            "acceptance_criteria": [
                "정합성 검증 규칙 10개 이상 구현",
                "검증 실패 시 상세 리포트 생성",
            ],
            "createdAt": "2025-03-05",
        },
    ],
    "budget_items": [
        {
            "id": "1",
            "projectId": "proj-1",
            "projectName": "AI 챗봇 플랫폼",
            "department": "개발팀",
            "category": "development",
            "plannedAmount": 50_000_000,
            "actualAmount": 42_000_000,
            "approvedAmount": 50_000_000,
            "remainingAmount": 8_000_000,
            "startDate": "2024-01-15",
            "endDate": "2024-03-30",
            "status": "in_progress",
            "description": "고객 서비스용 AI 챗봇 시스템 개발",
            "manMonths": 12,
            "hourlyRate": 50_000,
            "actualHours": 840,
        },
        {
            "id": "2",
            "projectId": "proj-2",
            "projectName": "모바일 앱 리뉴얼",
            "department": "UX팀",
            "category": "design",
            "plannedAmount": 30_000_000,
            "actualAmount": 28_000_000,
            "approvedAmount": 30_000_000,
            "remainingAmount": 2_000_000,
            "startDate": "2024-02-01",
            "endDate": "2024-04-15",
            "status": "in_progress",
            "description": "기존 모바일 앱의 UI/UX 개선",
            "manMonths": 8,
            "hourlyRate": 45_000,
            "actualHours": 622,
        },
        {
            "id": "3",
            "projectId": "proj-3",
            "projectName": "데이터 분석 시스템",
            "department": "데이터팀",
            "category": "infrastructure",
            "plannedAmount": 80_000_000,
            "actualAmount": 95_000_000,
            "approvedAmount": 80_000_000,
            "remainingAmount": -15_000_000,
            "startDate": "2024-01-01",
            "endDate": "2024-05-31",
            "status": "over_budget",
            "description": "빅데이터 분석을 위한 시스템 구축",
            "manMonths": 20,
            "hourlyRate": 55_000,
            "actualHours": 1_727,
        },
        {
            "id": "4",
            "projectId": "proj-4",
            "projectName": "마케팅 캠페인",
            "department": "마케팅팀",
            "category": "marketing",
            "plannedAmount": 25_000_000,
            "actualAmount": 25_000_000,
            "approvedAmount": 25_000_000,
            "remainingAmount": 0,
            "startDate": "2024-03-01",
            "endDate": "2024-03-31",
            "status": "completed",
            "description": "신제품 런칭 마케팅 캠페인",
            "manMonths": 3,
            "hourlyRate": 40_000,
            "actualHours": 625,
        },
    ],
    "budget_trend": [
        {"month": "1월", "planned": 180_000_000, "actual": 165_000_000},
        {"month": "2월", "planned": 210_000_000, "actual": 198_000_000},
        {"month": "3월", "planned": 230_000_000, "actual": 240_000_000},
        {"month": "4월", "planned": 250_000_000, "actual": 255_000_000},
        {"month": "5월", "planned": 260_000_000, "actual": 245_000_000},
        {"month": "6월", "planned": 280_000_000, "actual": 270_000_000},
    ],
    "executive": {
        "kpis": [
            {
                "id": "delivery_rate",
                "title": "정시 배포율",
                "value": 92,
                "target": 90,
                "unit": "%",
                "trend": "up",
                "trendValue": 2,
                "description": "계획된 일정 내 프로젝트 배포 성공률",
                "category": "operational",
            },
            {
                "id": "budget_efficiency",
                "title": "예산 효율성",
                "value": 87,
                "target": 85,
                "unit": "%",
                "trend": "up",
                "trendValue": 5,
                "description": "예산 대비 실제 지출 효율성",
                "category": "financial",
            },
            {
                "id": "roi",
                "title": "평균 ROI",
                "value": 145,
                "target": 120,
                "unit": "%",
                "trend": "up",
                "trendValue": 15,
                "description": "프로젝트 투자 대비 수익률",
                "category": "financial",
            },
            {
                "id": "quality_score",
                "title": "품질 점수",
                "value": 4.2,
                "target": 4.0,
                "unit": "/5.0",
                "trend": "up",
                "trendValue": 0.3,
                "description": "프로젝트 품질 종합 점수",
                "category": "quality",
            },
            {
                "id": "team_productivity",
                "title": "팀 생산성",
                "value": 78,
                "target": 75,
                "unit": "pts/sprint",
                "trend": "up",
                "trendValue": 8,
                "description": "스프린트당 평균 완료 스토리 포인트",
                "category": "operational",
            },
            {
                "id": "risk_mitigation",
                "title": "리스크 완화율",
                "value": 85,
                "target": 80,
                "unit": "%",
                "trend": "stable",
                "trendValue": 0,
                "description": "식별된 리스크 중 완화된 비율",
                "category": "strategic",
            },
        ],
        "portfolio": [
            {
                "projectId": "1",
                "projectName": "AI 챗봇 플랫폼",
                "department": "개발팀",
                "budget": 500_000,
                "spent": 420_000,
                "completion": 85,
                "status": "on_track",
                "roi": 165,
                "startDate": "2024-01-15",
                "endDate": "2024-03-30",
            },
            {
                "projectId": "2",
                "projectName": "모바일 앱 리뉴얼",
                "department": "UX팀",
                "budget": 300_000,
                "spent": 280_000,
                "completion": 75,
                "status": "at_risk",
                "roi": 120,
                "startDate": "2024-02-01",
                "endDate": "2024-04-15",
            },
            {
                "projectId": "3",
                "projectName": "데이터 분석 시스템",
                "department": "데이터팀",
                "budget": 800_000,
                "spent": 650_000,
                "completion": 60,
                "status": "delayed",
                "roi": 200,
                "startDate": "2024-01-01",
                "endDate": "2024-05-31",
            },
        ],
        "trend": [
            {"month": "1월", "revenue": 1_200_000, "cost": 800_000, "projects": 8, "completion": 85},
            {"month": "2월", "revenue": 1_350_000, "cost": 850_000, "projects": 10, "completion": 88},
            {"month": "3월", "revenue": 1_180_000, "cost": 900_000, "projects": 12, "completion": 82},
            {"month": "4월", "revenue": 1_480_000, "cost": 950_000, "projects": 14, "completion": 90},
            {"month": "5월", "revenue": 1_620_000, "cost": 1_000_000, "projects": 16, "completion": 92},
            {"month": "6월", "revenue": 1_750_000, "cost": 1_100_000, "projects": 18, "completion": 87},
        ],
    },
    "risk": {
        "4": {
            "predictedCompletionDate": "2025-12-15",
            "delayDays": 5,
            "overallRiskScore": 68,
            "completionProbability": 78,
            "totalTasks": 23,
            "completedTasks": 8,
            "highRiskTasks": 6,
            "teamUtilization": 82,
        },
        "1": {
            "predictedCompletionDate": "2024-06-25",
            "delayDays": -5,
            "overallRiskScore": 25,
            "completionProbability": 95,
            "totalTasks": 12,
            "completedTasks": 12,
            "highRiskTasks": 0,
            "teamUtilization": 65,
        },
    },
    "risk_insights": {
        "4": [
            {
                "id": "1",
                "type": "critical",
                "title": "핵심 기술 스택 경험 부족",
                "description": "OCR 모델 훈련 작업에 할당된 김AI개발님이 관련 기술 스택(TensorFlow, OpenCV) 경험이 제한적입니다.",
                "impact": "high",
                "actionable": True,
            },
            {
                "id": "2",
                "type": "warning",
                "title": "의존성 작업 지연 위험",
                "description": "데이터베이스 스키마 설계가 지연되면 하위 3개 작업에 연쇄적 영향이 예상됩니다.",
                "impact": "medium",
                "actionable": True,
            },
            {
                "id": "3",
                "type": "info",
                "title": "팀 업무 분배 불균형",
                "description": "김AI개발님의 업무 부하가 82%로 높은 반면, 일부 팀원은 50% 미만입니다.",
                "impact": "medium",
                "actionable": True,
            },
        ],
        "1": [
            {
                "id": "1",
                "type": "info",
                "title": "프로젝트 성공적 완료",
                "description": "모든 작업이 계획보다 5일 일찍 완료되어 높은 성과를 달성했습니다.",
                "impact": "low",
                "actionable": False,
            }
        ],
    },
    "quality_metrics": {
        "4": {
            "codeComplexity": 7.2,
            "testCoverage": 78,
            "bugDensity": 0.8,
            "duplicateCodeRate": 3.2,
            "codeSmells": 12,
            "technicalDebt": 2.5,
            "performanceScore": 85,
            "securityScore": 92,
            "maintainabilityIndex": 76,
        },
        "1": {
            "codeComplexity": 5.8,
            "testCoverage": 95,
            "bugDensity": 0.2,
            "duplicateCodeRate": 1.8,
            "codeSmells": 3,
            "technicalDebt": 0.8,
            "performanceScore": 94,
            "securityScore": 98,
            "maintainabilityIndex": 89,
        },
    },
    "quality_trends": {
        "4": [
            {"date": "3월 1주", "complexity": 6.8, "coverage": 72, "bugs": 15, "performance": 82},
            {"date": "3월 2주", "complexity": 7.0, "coverage": 75, "bugs": 12, "performance": 83},
            {"date": "3월 3주", "complexity": 7.1, "coverage": 76, "bugs": 10, "performance": 84},
            {"date": "3월 4주", "complexity": 7.2, "coverage": 78, "bugs": 8, "performance": 85},
        ],
        "1": [
            {"date": "1월 1주", "complexity": 6.2, "coverage": 88, "bugs": 8, "performance": 90},
            {"date": "1월 2주", "complexity": 6.0, "coverage": 91, "bugs": 5, "performance": 92},
            {"date": "1월 3주", "complexity": 5.9, "coverage": 93, "bugs": 3, "performance": 93},
            {"date": "1월 4주", "complexity": 5.8, "coverage": 95, "bugs": 2, "performance": 94},
        ],
    },
    "file_quality": {
        "4": [
            {"file": "src/ml/ocr_model.py", "complexity": 25, "coverage": 45, "issues": 8, "size": 1_250, "risk": "critical"},
            {"file": "src/api/insurance_api.py", "complexity": 18, "coverage": 60, "issues": 5, "size": 890, "risk": "high"},
            {"file": "src/utils/data_processor.py", "complexity": 12, "coverage": 78, "issues": 2, "size": 650, "risk": "medium"},
            {"file": "src/web/dashboard.tsx", "complexity": 8, "coverage": 85, "issues": 1, "size": 420, "risk": "low"},
            {"file": "src/auth/auth_service.py", "complexity": 6, "coverage": 92, "issues": 0, "size": 310, "risk": "low"},
        ],
        "1": [
            {"file": "src/nlp/intent_classifier.py", "complexity": 8, "coverage": 95, "issues": 0, "size": 580, "risk": "low"},
            {"file": "src/api/chatbot_api.py", "complexity": 6, "coverage": 98, "issues": 0, "size": 420, "risk": "low"},
            {"file": "src/utils/text_processor.py", "complexity": 5, "coverage": 90, "issues": 1, "size": 320, "risk": "low"},
        ],
    },
    "code_analysis": {
        "4": {
            "totalLines": 45_680,
            "productionLines": 32_450,
            "testLines": 9_870,
            "commentLines": 3_360,
            "filesAnalyzed": 127,
            "lastAnalysis": "2025-03-27 09:30:00",
        },
        "1": {
            "totalLines": 12_340,
            "productionLines": 8_450,
            "testLines": 3_120,
            "commentLines": 770,
            "filesAnalyzed": 38,
            "lastAnalysis": "2024-06-15 14:20:00",
        },
    },
    "notifications": {
        "4": [
            {
                "id": "1",
                "type": "alert",
                "category": "code_quality",
                "title": "코드 복잡도 임계치 초과",
                "message": "김AI개발님의 PR #78에서 OCR 모델 파일의 복잡도가 25로 측정되어 임계치(15)를 초과했습니다.",
                "timestamp": "5분 전",
                "read": False,
                "actionable": True,
                "priority": "critical",
                "data": {
                    "file": "src/ml/ocr_model.py",
                    "complexity": 25,
                    "threshold": 15,
                    "author": "김AI개발",
                },
            },
            {
                "id": "2",
                "type": "warning",
                "category": "code_quality",
                "title": "테스트 커버리지 감소",
                "message": "보험 API 모듈의 테스트 커버리지가 85%에서 60%로 감소했습니다.",
                "timestamp": "15분 전",
                "read": False,
                "actionable": True,
                "priority": "high",
                "data": {
                    "module": "insurance_api",
                    "previousCoverage": 85,
                    "currentCoverage": 60,
                },
            },
            {
                "id": "3",
                "type": "warning",
                "category": "process",
                "title": "장기간 진행 중인 작업 감지",
                "message": "REQ-005 카카오 소셜 로그인 작업이 5일째 \"진행 중\" 상태입니다.",
                "timestamp": "1시간 전",
                "read": False,
                "actionable": True,
                "priority": "medium",
                "data": {
                    "taskId": "REQ-005",
                    "duration": 5,
                    "assignee": "김AI개발",
                },
            },
            {
                "id": "4",
                "type": "info",
                "category": "performance",
                "title": "성능 점수 개선",
                "message": "최근 최적화 작업으로 전체 성능 점수가 82에서 85로 향상되었습니다.",
                "timestamp": "2시간 전",
                "read": True,
                "actionable": False,
                "priority": "low",
                "data": {
                    "previousScore": 82,
                    "currentScore": 85,
                },
            },
            {
                "id": "5",
                "type": "warning",
                "category": "team",
                "title": "팀원 업무 과부하 감지",
                "message": "김AI개발님의 현재 업무 부하가 82%로 높은 수준입니다.",
                "timestamp": "3시간 전",
                "read": True,
                "actionable": True,
                "priority": "medium",
                "data": {
                    "member": "김AI개발",
                    "workload": 82,
                    "threshold": 80,
                },
            },
            {
                "id": "6",
                "type": "info",
                "category": "security",
                "title": "보안 스캔 완료",
                "message": "정기 보안 스캔이 완료되었습니다. 새로운 취약점은 발견되지 않았습니다.",
                "timestamp": "4시간 전",
                "read": True,
                "actionable": False,
                "priority": "low",
            },
        ],
        "1": [
            {
                "id": "1",
                "type": "success",
                "category": "code_quality",
                "title": "코드 품질 목표 달성",
                "message": "모든 품질 지표가 목표치를 상회하여 프로젝트가 성공적으로 완료되었습니다.",
                "timestamp": "1일 전",
                "read": True,
                "actionable": False,
                "priority": "low",
            }
        ],
    },
    "integrations": [
        {
            "id": "slack",
            "name": "Slack",
            "description": "팀 커뮤니케이션 및 알림 연동",
            "category": "communication",
            "status": "connected",
            "isEnabled": True,
            "lastSync": "2024-12-27 14:30:00",
            "features": ["실시간 알림", "작업 생성", "상태 업데이트", "보고서 공유"],
            "webhookUrl": "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXX",
            "config": {
                "channel": "#project-updates",
                "botToken": "xoxb-xxxxxxxxxxxx-xxxxxxxxxxxx-xxxxxxxxxxxxxxxx",
                "enableMentions": True,
                "notificationTypes": ["task_created", "task_completed", "risk_detected"],
            },
        },
        {
            "id": "teams",
            "name": "Microsoft Teams",
            "description": "Microsoft Teams 채널 연동",
            "category": "communication",
            "status": "disconnected",
            "isEnabled": False,
            "features": ["채널 알림", "회의 일정 연동", "파일 공유"],
            "config": {},
        },
        {
            "id": "github",
            "name": "GitHub",
            "description": "GitHub 리포지토리 및 커밋 추적",
            "category": "development",
            "status": "connected",
            "isEnabled": True,
            "lastSync": "2024-12-27 15:00:00",
            "features": ["커밋 추적", "이슈 연동", "PR 관리", "코드 품질 분석"],
            "config": {
                "repositories": ["myorg/project-a", "myorg/project-b"],
                "accessToken": "ghp_xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "trackBranches": ["main", "develop"],
                "enableWebhooks": True,
            },
        },
        {
            "id": "gitlab",
            "name": "GitLab",
            "description": "GitLab 프로젝트 연동",
            "category": "development",
            "status": "error",
            "isEnabled": False,
            "features": ["소스 코드 관리", "파이프라인 추적", "이슈 관리"],
            "config": {},
        },
        {
            "id": "bitbucket",
            "name": "Bitbucket",
            "description": "Bitbucket 리포지토리 연동",
            "category": "development",
            "status": "disconnected",
            "isEnabled": False,
            "features": ["리포지토리 동기화", "PR 추적", "브랜치 관리"],
            "config": {},
        },
        {
            "id": "confluence",
            "name": "Confluence",
            "description": "문서 협업 및 지식 관리",
            "category": "documentation",
            "status": "connected",
            "isEnabled": True,
            "lastSync": "2024-12-27 13:45:00",
            "features": ["문서 검색", "요구사항 연동", "AI 지식 베이스", "자동 문서화"],
            "config": {
                "spaceKey": "PROJ",
                "baseUrl": "https://company.atlassian.net/wiki",
                "apiToken": "ATATT3xFfGF0T...",
                "enableSearch": True,
                "syncPages": ["requirements", "specifications", "meeting-notes"],
            },
        },
        {
            "id": "notion",
            "name": "Notion",
            "description": "Notion 워크스페이스 연동",
            "category": "documentation",
            "status": "pending",
            "isEnabled": False,
            "features": ["페이지 동기화", "데이터베이스 연동", "템플릿 관리"],
            "config": {},
        },
    ],
    "integration_logs": [
        {
            "id": "log-1",
            "integrationId": "slack",
            "type": "webhook",
            "message": "task_created 이벤트가 Slack 채널로 전송되었습니다.",
            "timestamp": "2024-12-27 15:05:00",
            "status": "success",
            "details": {"taskId": "4-1", "channel": "#project-updates"},
        },
        {
            "id": "log-2",
            "integrationId": "github",
            "type": "sync",
            "message": "myorg/project-a 레포지토리에서 3개의 커밋이 동기화되었습니다.",
            "timestamp": "2024-12-27 15:00:00",
            "status": "success",
            "details": {"commitCount": 3, "status": "ok"},
        },
        {
            "id": "log-3",
            "integrationId": "gitlab",
            "type": "error",
            "message": "GitLab API 호출 중 인증 오류가 발생했습니다.",
            "timestamp": "2024-12-27 14:45:00",
            "status": "error",
            "details": {"status_code": 401, "error": "Unauthorized"},
        },
    ],
}


def load_seed_data() -> Dict[str, Any]:
    """Return a deep copy of the seed data so callers can mutate it safely."""

    return deepcopy(SEED_DATA)
